config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index' #Esta es la que deberia ir, vista home
  resources :profiles do
  	resources :images
    resources :bank_accounts
    resources :paypal_accounts
    resources :coffee_donations
    resources :hug_donations
    resources :donations
    get 'donate', to: 'donations#index'
    get 'greetings', to: 'donations#greetings'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  enum kind: {'Corriente': 0, 'Ahorros': 1}
  enum bankname: {
    'Banesco': '0',
    'Banco de Venezuela': '1',
    'Banco Exterior': '2',
    'Banco Mercantil': '3',
    'Banco Bicentenario': '4',
    'Banco Venezolano de Crédito': '5',
    'Banco Provincial': '6',
    'Banco del Tesoro': '7',
    '100% Banco': '8',
    'Banco Activo': '9'
  }

  belongs_to :user

  validates :bankname, :account_number, :owner_fullname, :identification_number, :kind, :owner_email, presence: true
  # validates :email, format: {with: "/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/", message: "Formato de Email Incorrecto"}

end

app/models/coffee_donation.rb
class CoffeeDonation < ApplicationRecord
  belongs_to :donation

  accepts_nested_attributes_for :donation, reject_if: :all_blank
end

app/models/donation.rb
class Donation < ApplicationRecord
  enum kind: {'coffee': '0', 'hug': '1'}

  belongs_to :profile

  has_many :hug_donations
  has_many :coffee_donations

  validates :full_name, :role, :gretting_message, presence: true
end

app/models/hug_donation.rb
class HugDonation < ApplicationRecord
  belongs_to :donation
end

app/models/image.rb
class Image < ApplicationRecord
	enum visible: {'0': 'false', '1': 'true'}

  belongs_to :profile
  has_one_attached :picture

  validates :subtitle, :picture, presence: true
  validate :correct_file_type
  validate :add_picture?

  private

  def correct_file_type
    if picture.attached? && !picture.content_type.in?(%w(image/jpg image/jpeg image/png image/svg+xml))
      errors.add(:picture, 'Seleccionar solo archivos con extensión .jpg / .jpeg / .png / .svg')
    end
  end

  def add_picture?
    errors.add(:picture, 'debe ser incluida.') unless picture.attached?
  end
end

app/models/paypal_account.rb
class PaypalAccount < ApplicationRecord
  belongs_to :user

  validates :email, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
  has_many :images
  has_many :donations

  validates :full_name, :role, :biography, :coffee_price, :currency, :multia, :multib, :multic, :multid, presence: true
  validates :coffee_price, numericality: true
  validates :multia, :multib, :multic, :multid, numericality: { greater_than: 0 }
  validate :correct_file_type

  private

  def correct_file_type
    if avatar.attached? && !avatar.content_type.in?(%w(image/jpg image/jpeg image/png))
      errors.add(:avatar, 'Seleccionar solo archivos con extensión .jpg / .jpeg / .png')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  has_one :profile
  has_one :paypal_account
  has_many :bank_accounts

  validates :email, uniqueness: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :new_user_block
  def index
    @user = current_user
  end

  private
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	layout 'admin'
	before_action :new_user_block
	before_action :set_image, only: [:edit, :update, :destroy]
	before_action :set_profile, except: [:index, :create]
	before_action :set_current_user_profile

	def index
		@profile = Profile.find(params[:profile_id])
    @images = @profile.images.where(profile_id: @profile)
	end

	def new
		@profile = Profile.find(params[:profile_id])
		@image = Image.new()
	end

	def edit

	end

	def create
		@profile = Profile.find(params[:profile_id])
    @image = @profile.images.build(image_params)
    respond_to do |format|
      if @image.save
        format.html { redirect_to profile_images_path, notice: '¡ Imagen Agregada Correctamente !' }
      else
        format.html { render :edit }
      end
    end
	end

	def update
		respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to profile_images_path(@image.profile), notice: '¡ Imagen Actualizada Correctamente !' }
      else
        format.html { render :edit }
      end
    end
	end

	def destroy
		respond_to do |format|
      if @image.destroy
        format.html { redirect_to profile_images_path, notice: '¡ Imagen del carrusel eliminada !'}
      else
        format.html { redirect_to profile_images_path, notice: '¡ No se pudo eliminar la imagen !'}
      end
	  end
	end

	private

	def set_image
		@image = Image.find(params[:id])
	end

	def set_profile
    @profile = Profile.find_by(params[:profile_id])
  end

	def image_params
		params.require(:image).permit(:subtitle, :visible, :picture)
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  layout :resolve_layout
  before_action :new_user_block, except: [:new, :create]
  before_action :set_profile, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]
  before_action :set_current_user_profile, only: [:edit, :update]

	def index

	end

	def new
    @user = current_user
    if @user.profile.nil?
      @user = User.find current_user.id
      @profile = @user.build_profile
    else
      redirect_to root_path
    end
	end

	def show
	  @profile = Profile.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @profile }
    end
	end

	def create
		@user = current_user
		@profile = @user.build_profile(profile_params)
    respond_to do |format|
      if @profile.save
        if @profile.avatar.attached?
          format.html { redirect_to edit_profile_path(@user.profile.id), notice: '¡ Perfil Creado Correctamente !' }
        else
          @profile.avatar.attach(io: File.open(Rails.root.join("app", "assets", "images", "default_avatar.png")), filename: 'default_avatar.png' , content_type: "image/png")
          format.html { redirect_to edit_profile_path(@user.profile.id), notice: '¡ Perfil Creado Correctamente !' }
        end
      else
        format.html { redirect_to new_profile_path, alert: 'Todos los campos son requeridos'}
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to edit_profile_path, notice: '¡ Perfil Actualizado Correctamente !' }
      else
        format.html { render :edit }
      end
    end
  end

	private

	def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:full_name, :role, :biography, :coffee_price, :currency, :multia, :multib, :multic, :multid, :avatar)
  end

  def resolve_layout
    case action_name
    when "new", "create", "edit", "update"
      "admin"
    when "show", "setdonation"
      "mobile"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hug_donations_helper.rb
module HugDonationsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/paypal_accounts_helper.rb
module PaypalAccountsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Hugs & Coffee
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Happy+Monkey", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto", :rel => "stylesheet"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.d-flex.justify-content-around
    .row.adminpage
      .col-2.sidebar
        = render 'shared/sidebaradmin', user: current_user
      .col-10.section
        = render 'shared/headeradmin', user: current_user
        .container
          = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    %title Hugs & Coffee
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Happy+Monkey", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto", :rel => "stylesheet"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{data_controller: controller_name}
    .container-fluid
      = render 'shared/headerhome', user: current_user
      #error= render 'shared/alerterror' if (flash[:alert])
      = yield

app/views/layouts/mobile.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    %script{:src => "jquery.bcSwipe.js"}
    %title Hugs & Coffee
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Happy+Monkey", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto", :rel => "stylesheet"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{data_controller: controller_name}
    .container-fluid
      .row
        .col-12.showprofile
          = render 'shared/headermobile'
          = yield

app/views/shared/_accountform.html.haml
.mt-2
  %p= link_to '< Configuración', new_profile_bank_account_path(@profile), style: "text-decoration: none; color: #566073;"
%h3.font-roboto-title Cuentas bancarias
%hr
#notice= render 'shared/alertsuccess' if (flash[:notice])
#error= render 'shared/alerterror' if (flash[:alert])
= form_with(model: [@profile, @account], local: true ) do |form|
  - if @account.errors.any?
    #error_explanation.alert.alert-danger.alert-dismissible.fade.show.font-happy-alert
      %h4= "#{pluralize(@account.errors.count, "error")} al intentar guardar la cuenta:"
      %ul
        - @account.errors.full_messages.each do |message|
          %li= message
      %button.close{ 'data-dismiss': 'alert' }
        %span x
  .row.mt-5.mb-5
    .col-4
      %h5.font-roboto-form Agregar cuenta bancaria
      %p.font-roboto-p Puedes agregar varias cuentas bancarias asociadas a tu perfil y permitir a tu amigos recibir donaciones de Abrazos y Cafés.
      -if @user.paypal_account.nil?
        .row.justify-content-center.mt-5
          .col-7
            .card
              .card-header
                %h3.font-roboto-bold.text-center Cuenta
                = image_tag ('paypal.png'), class: 'img-fluid card-img-top', height:'25px', width: '75px'
              .card-title.text-center
                =link_to 'Agregar', new_profile_paypal_account_path(@profile), class: 'btn botonpaypal mt-3'
      - else
        .row.justify-content-center.mt-5
          .col-7
            .card
              .card-header
                %h3.font-roboto-bold.text-center Cuenta
                = image_tag ('paypal.png'), class: 'img-fluid card-img-top'
              .card-body.text-center
                %p.font-roboto-form= @user.paypal_account.email
              .card-footer.text-center
                =link_to 'Editar', edit_profile_paypal_account_path(@profile,@user.paypal_account), class: 'btn botonpaypal'

    .col-8
      .card.rounded
        .card-body
          .row.form-group
            .col-12.form-label
              .font-roboto-form= form.label :bankname, 'Banco'
              = form.select :bankname, BankAccount.banknames.keys.map { |bankname| [bankname.titleize, bankname]}, {include_blank: true}, {class: 'form-control custom-select', required: 'true'}
          .row.form-group
            .col-12.form-label
              .font-roboto-form= form.label :account_number, 'Número de Cuenta'
              #msgaccount
              #accountnumber= form.text_field :account_number, class: 'form-control', type: 'text', maxlength: '24', pattern: '^(\d{4}-)+(\d{4}-)+(\d{4}-)+(\d{4}-)+(\d{4})$', title: 'Formato de cuenta Inválido', required: 'true'
              .font-roboto-light.text-right.mt-2= form.label 'Ejemplo: 0000-1111-2222-3333-4444'
          .row.form-group
            .col-12.form-label
              .font-roboto-form= form.label :owner_fullname, 'Titular de la cuenta'
              = form.text_field :owner_fullname, class: 'form-control', required: 'true'
          .row.form-group
            .col-12.form-label
              .font-roboto-form= form.label :identification_number, 'Cédula / RIF'
              #msgid
              #accountid= form.text_field :identification_number, class: 'form-control', maxlength: '11', pattern: '^([JVE]-)[0-9]{1,9}$', title: 'Formato de cédula Inválido', required: 'true'
              .font-roboto-light.text-right.mt-2= form.label 'Ejemplo: J-123456789 / V-12345678'
          .row.form-group
            .col-12.form-label
              .font-roboto-form= form.label :kind, 'Tipo de Cuenta'
              = form.select :kind, BankAccount.kinds.keys.map { |kind| [kind.titleize, kind]}, {include_blank: true}, {class: 'form-control custom-select', required: 'true'}
          .row.form-group
            .col-12.form-label
              .font-roboto-form= form.label :owner_email, 'Correo electrónico'
              #msgemailacc
              #emailacc= form.text_field :owner_email, class: 'form-control', pattern: "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$", title: 'Formato de correo electrónico inválido', required: 'true'
          .row.form-group.justify-content-center.mt-4
            .col-sm-12
              .actions
                .text-right= form.submit 'Guardar', class: 'savebutton font-roboto-button'

app/views/shared/_alert.html.haml
.alert.alert-warning.alert-dismissible.fade.show
  .font-happy-alert.text-danger= devise_error_messages!
  %button.close{ 'data-dismiss': 'alert' }
    %span x

app/views/shared/_alerterror.html.haml
.alert.alert-danger.alert-dismissible.fade.show
  .font-happy-alert= flash[:alert]
  %button.close{ 'data-dismiss': 'alert' }
    %span x

app/views/shared/_alertsession.html.haml
#error_explanation
  .alert.alert-warning.alert-dismissible.fade.show
    %h5.font-happy.text-center.text-danger= "! #{flash.alert} ¡"
    %button.close{ 'data-dismiss': 'alert' }
      %span x

app/views/shared/_alertsuccess.html.haml
.alert.alert-success.alert-dismissible.fade.show
  .font-happy-alert= notice
  %button.close{ 'data-dismiss': 'alert' }
    %span x

app/views/shared/_form.html.haml
.col.mt-3
  %h3.font-roboto-title Perfil de Usuario
  %hr
  #notice= render 'shared/alertsuccess' if (flash[:notice])
  #error= render 'shared/alerterror' if (flash[:alert])
  = form_with(model: @profile, local: true ) do |form|
    - if @profile.errors.any?
      #error_explanation.alert.alert-danger.alert-dismissible.fade.show.font-happy-alert
        %h4= "#{pluralize(@profile.errors.count, "error")} al intentar guardar el perfil:"
        %ul
          - @profile.errors.full_messages.each do |message|
            %li= message
        %button.close{ 'data-dismiss': 'alert' }
          %span x

    .row.mt-5.mb-5
      .col-8
        .card.rounded
          .card-body.mb-2
            .row.form-group
              .col-sm-6.col-form-label
                .font-roboto-form= form.label :full_name, 'Nombre y apellido'
                = form.text_field :full_name, class: 'form-control', required: 'true'
              .col-sm-6.col-form-label
                .font-roboto-form= form.label :role, 'Ocupación'
                = form.text_field :role, class: 'form-control', required: 'true'
            .row.form-group
              .col-sm-12.col-form-label
                .font-roboto-form= form.label :biography , 'Biografía:'
                = form.hidden_field :biography, class: 'form-control', id: 'wys', required: 'true'
                %trix-editor.trix-editor{input:'wys'}
            .row.form-group
              .col-sm-12.col-form-label
                .font-roboto-form= form.label :avatar, 'Foto de Perfil:'
                = form.file_field :avatar, class: 'dropify'
      .col-4
        .card.rounded
          .card-body
            .row.form-group
              .col-sm-12.col-form-label
                .font-roboto-form= form.label :coffee_price, 'Monto de un Café:'
                = form.number_field :coffee_price, class: 'form-control', min: 1, max: 1000000, step: 'any', required: 'true'
            .row.form-group
              .col-sm-12.col-form-label
                .font-roboto-form= form.label :currency, 'Símbolo de la moneda'
                = form.text_field :currency, class: 'form-control', required: 'true'
            .row.form-group
              .col-sm-12.col-form-label
                .font-roboto-form= form.label :multiplier, 'Multiplicadores'
              .col-sm-3
                .multiplier= form.number_field :multia, class: 'form-control', id: 'multiplicador', maxlength: 2, min: 1, max: 99, placeholder: 1, required: 'true'
              .col-sm-3
                .multiplier= form.number_field :multib, class: 'form-control', id: 'multiplicador', maxlength: 2, min: 1, max: 99, placeholder: 2, required: 'true'
              .col-sm-3
                .multiplier= form.number_field :multic, class: 'form-control', id: 'multiplicador', maxlength: 2, min: 1, max: 99, placeholder: 3, required: 'true'
              .col-sm-3
                .multiplier= form.number_field :multid, class: 'form-control', id: 'multiplicador', maxlength: 2, min: 1, max: 99, placeholder: 4, required: 'true'
              -if action_name == 'edit'
                .container
                  .row.justify-content-center.mt-5
                    .col-6
                      .card.rounded
                        .card-header
                          = image_tag (url_for(@profile.avatar)), class: 'img-fluid card-img-top'
                        .card-title.text-center
                          %h6.mt-3.font-happy-bold Mi Avatar
    %hr
    .row.form-group.justify-content-center.mt-4
      .col-sm-12
        .actions
          .text-right= form.submit 'Guardar', class: 'savebutton font-roboto-button'

app/views/shared/_headeradmin.html.haml
.row.sectionnavbar.navbar.navbar-expand-lg
  .col-9.inputrectangle
    %form
      %input{:type => "text", :class => "navbarinput", :disabled => 'true'}
  .col-3.profile-session
    .row
    - if user.profile.present?
      .col-4
        = image_tag (user.profile.avatar), class: 'avatar'
    - else
      .col-4
        = image_tag ('default_avatar.png'), class: 'avatar'
    - if ((controller_name == 'profiles') || (controller_name == 'images') || (controller_name == 'bank_accounts') || (controller_name == 'paypal_accounts'))
      .col-8.profilefullname
        %nav.navbar.navbar-expand.navbar-light
          .collapse.navbar-collapse#navbarDropdownprofile
            %ul.navbar-nav
              %li.nav-item.dropdown
              -if(action_name == 'new' && (controller_name == 'profiles'))
                %a#navbarDropdownprofile.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                  = user.email
                .dropdown-menu#hola{"aria-labelledby" => "navbarDropdown"}
                  .dropdown-item#colorpink= link_to "Cerrar Sesión", destroy_user_session_path, method: 'delete', id: 'prueba2'
              -else
                %a#navbarDropdownprofile.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                  = user.profile.full_name
                .dropdown-menu#hola{"aria-labelledby" => "navbarDropdown"}
                  .dropdown-item#colorpink=link_to "Ir a su Perfil", profile_path(@profile.id), id: 'prueba2'
                  .dropdown-divider
                  .dropdown-item#colorpink= link_to "Cerrar Sesión", destroy_user_session_path, method: 'delete', id: 'prueba2'

app/views/shared/_headermobile.html.haml
.showprofileheader
  .row
    .col-9.profileinfo
      .row.mt-1
        .col-4.d-flex.align-items-center
          .showprofileavatar
            = image_tag (@profile.avatar), class: 'avatarprofilemobile', id: 'avatarprofilemobile'
        .col-8.d-flex.flex-column.justify-content-center
          .row
            .showprofilefullname
              = @profile.full_name
          .row
            .showprofileoccupation
              = @profile.role
    .col-3.homebutton.d-flex.align-items-center
      = link_to "A&C", root_path, class: 'btn logobuttonmobile'

app/views/shared/_listaccounts.html.haml
.row.mt-5.mb-5
  .col-4
    %h5.font-roboto-form Cuenta Bancarias
    %p.font-roboto-p Listado de cuentas bancarias asociadas a tú perfil.
  .col-8
    .card.rounded
      .card-body
        .font-roboto-form.row
          .col-3
            Banco
          .col-5
            N° de Cuenta
          .col-4
            Tipo
        %hr
        -if @accounts
          - @accounts.each do |account|
            .row
              .col-3
                = account.bankname
              .col-5
                = account.account_number
              .col-2
                = account.kind
              .col-2
                .dropdown.dropleft
                  %button#dropdownMenuButton.btn{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
                    = image_tag 'cardmenubutton.svg', class: 'cardmenubutton'
                  .dropdown-menu#hola{"aria-labelledby" => "dropdownMenuButton"}
                    .dropdown-item#colorpink
                      =link_to edit_profile_bank_account_path(@profile.id,account), class: 'cardmenubuttonpopupitem', id: 'editbutton' do
                        .row
                          .col-3
                            = image_tag 'pencil.svg'
                          .col-9
                            Editar
                    .dropdown-item#colorpink
                      =link_to profile_bank_account_path(@profile.id,account), method: :delete, data: { confirm: '¿Esta seguro de eliminar esta cuenta?'}, class: 'cardmenubuttonpopupitem', id: 'editbutton' do
                        .row
                          .col-3
                            = image_tag 'bin2.svg'
                          .col-9
                            Eliminar

app/views/shared/_paypalform.html.haml
.mt-2
  %p= link_to '< Regresar', new_profile_bank_account_path(@profile), style: "text-decoration: none; color: #566073;"
%h3.font-roboto-title Cuenta Paypal
%hr
#notice= render 'shared/alertsuccess' if (flash[:notice])
= form_with(model: [@profile, @paypal], local: true ) do |form|
  - if @paypal.errors.any?
    #error_explanation.alert.alert-danger.alert-dismissible.fade.show.font-happy-alert
      %h4= "#{pluralize(@paypal.errors.count, "error")} al intentar guardar la cuenta:"
      %ul
        - @paypal.errors.full_messages.each do |message|
          %li= message
      %button.close{ 'data-dismiss': 'alert' }
        %span x
  .row.mt-5.mb-5
    .col-4
      %h5.font-roboto-form Agregar cuenta Paypal
      %p.font-roboto-p Puedes agregar una cuenta Paypal asociada a tu perfil y permitir a tu amigos recibir donaciones de Abrazos y Cafés.
    .col-8
      .card.rounded
        .card-body
          .row.form-group
            .col-12.form-label
              .font-roboto-form= form.label :email, 'Correo Electrónico de Paypal'
              #emailpaypal= form.text_field :email, class: 'form-control', pattern: "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$", title: 'Formato de correo electrónico'
              #msgemailpaypal.mt-2
          .row.form-group.justify-content-center.mt-4
            .col-sm-12
              .actions
                .text-right= form.submit 'Guardar', class: 'savebutton font-roboto-button'

app/views/shared/_sidebaradmin.html.haml
.row.sidebarheader
  .col-12.text-center.mt-2
    = link_to "A&C", root_path, class: 'logolink'
.row.sidebarmenu
  %ul.sidebarmenuul.col-12.mr-5
    - if controller_name == 'profiles' && action_name == 'new'
      %li.sidebarmenuli.col-12.mt-3
        .row
          .col-2.iconsidebaradmin
            = image_tag ('perfilpink.svg')
          .col-10.sidebarmenulipink
            Perfil
      %li.sidebarmenuli.col-12.mt-3
        .row
          .col-2.iconsidebaradmin
            = image_tag ('perfil.svg')
          .col-10
            Imágenes
      %li.sidebarmenuli.col-12.mt-3
        .row
          .col-2.iconsidebaradmin
            = image_tag ('cuentas.svg')
          .col-10
            Cuentas
    -else
      - if controller_name == 'profiles'
        %li.sidebarmenuli.col-12.mt-3
          .row
            .col-2.iconsidebaradmin
              = image_tag ('perfilpink.svg')
            .col-10.sidebarmenulipink
              Perfil
      - else
        %li.sidebarmenuli.col-12.mt-3
          = link_to edit_profile_path(id: params[:profile_id]), class: 'sidebarmenulink' do
            .row
              .col-2.iconsidebaradmin
                = image_tag ('perfil.svg')
              .col-10
                Perfil
      - if controller_name == 'images'
        %li.sidebarmenuli.col-12.mt-3
          .row
            .col-2.iconsidebaradmin
              = image_tag ('perfilpink.svg')
            .col-10.sidebarmenulipink.mt-1
              Imágenes
      - else
        %li.sidebarmenuli.col-12.mt-3
          = link_to profile_images_path(@profile), class: 'sidebarmenulink' do
            .row
              .col-2.iconsidebaradmin
                = image_tag ('perfil.svg')
              .col-10
                Imágenes
      - if controller_name == 'bank_accounts'
        %li.sidebarmenuli.col-12.mt-3
          .row
            .col-2.iconsidebaradmin
              = image_tag ('cuentaspink.svg')
            .col-10.sidebarmenulipink
              Cuentas
      - else
        %li.sidebarmenuli.col-12.mt-3
          = link_to new_profile_bank_account_path(@profile), class: 'sidebarmenulink' do
            .row
              .col-2.iconsidebaradmin
                = image_tag ('cuentas.svg')
              .col-10
                Cuentas