config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index' #Esta es la que deberia ir, vista home
  resources :profiles do
  	resources :images
    resources :bank_accounts
    resources :paypal_accounts
    resources :coffee_donations
    resources :hug_donations
    resources :donations
    get 'donate', to: 'donations#index'
    get 'greetings', to: 'donations#greetings'
  end
end

app/models/donation.rb
class Donation < ApplicationRecord
  enum kind: {'coffee': '0', 'hug': '1'}

  belongs_to :profile

  has_many :hug_donations
  has_many :coffee_donations

  validates :full_name, :role, :gretting_message, presence: true
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  layout 'mobile'
  before_action :set_profile
  before_action :set_paypal_account, only: [:new, :index]
  before_action :set_current_user, only: [:new, :index]
  before_action :set_account, only: [:new, :index]
  before_action :authenticate_user!, except: [:new, :index]

  def index
    @accounts = BankAccount.all.where(user_id: @user)
    @paypals = PaypalAccount.all.where(user_id: @user)
  end

  def new
    @paypals = PaypalAccount.all.where(user_id: @user)
    @donation = Donation.new
  end

  def create
    @donation = @profile.donations.build(donation_params)
    if @donation.save
      redirect_to profile_greetings_path(profile_id: @profile.id), notice: '¡ Agradecimiento Enviado Satisfactoriamente !'
    else
      render :new
    end
  end

  def greetings
    @profile = Profile.find(params[:profile_id])
  end

  private

  def set_donation
    @donation = Donation.find(params[:id])
  end

  def set_profile
    @profile = Profile.find(params[:profile_id])
  end

  def set_current_user
    @user = @profile.user_id
  end

  def set_account
    @accounts = BankAccount.all.where(user_id: @user)
  end

  def set_paypal_account
    @paypals = PaypalAccount.all.where(user_id: @user)
  end

  def donation_params
    params.require(:donation).permit(:full_name, :role, :gretting_message, :kind, :qty_coffee, :qty_hug)
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/greetings.html.haml
.container2
  .row.showprofilecontent.d-flex.justify-content-center
    .col.mt-2.col-sm-6
      .row.backbutton
        %p= link_to '< Perfil', profile_path(id: @profile.id), id: 'linkbackmobile'
      .row.cardimage.d-flex.justify-content-center.mt-3
        = image_tag ('heartcoffeesgreetings.svg'), class: 'mt-3'
      .row.greetingsmessage.mb-5.d-flex.justify-content-center.mt-1
        Gracias!
  

.row.showprofilefooter2.d-flex.fixed-bottom
  .col-12.textfootermobile.d-flex.align-items-center.justify-content-center#buttonfootertext2
    Righttocopy abrazosycafe.com

app/views/donations/index.html.haml
-# Index recognize donation
.row.showprofilecontent
  .col-12.mt-2.col-sm-8.offset-sm-2
    .row
      .col.col-md-6
        %p= link_to '< Atrás', profile_path(id: @profile.id), id: 'linkbackmobile'
    .row.mb-2
      .col.showprofilefullname
        Formas de reconocer a
        -name = @profile.full_name.split[0]
        = name
    .row
      .col-5.offset-1.cardsection.coffeecard
        = link_to new_profile_coffee_donation_path(@profile), id: 'waystoreconigzecardlink' do
          .card.mobilecard
            = image_tag ('coffee.svg'), class: 'mt-3'
            .cardtext.mb-2.mt-1.waystoreconigzecardtext
              Café
      .col-5.cardsection.hugcard
        = link_to new_profile_hug_donation_path(@profile), id: 'waystoreconigzecardlink' do
          .card.mobilecard
            = image_tag ('heart.svg'), class: 'mt-3'
            .cardtext.mb-2.mt-3.waystoreconigzecardtext
              Abrazo
    .row
      .col-12
        .donationsemptystate.d-flex.justify-content-center.mt-3.mb-3
          = image_tag ('donationsempty_state.svg')
    .row.selectiontext
      .col-12.mb-5
        Selecciona alguna de las dos opciones para continuar
.row.showprofilefooter2.d-flex.fixed-bottom
  .col-12.textfootermobile.d-flex.align-items-center.justify-content-center#buttonfootertext2
    Righttocopy abrazosycafe.com

app/views/donations/new.html.haml
.container.mt-2.showprofilecontent
  .row
    .col-12
      = link_to '< Atras', profile_donate_path(@profile), style: "text-decoration: none; color: #566073;"
      -name = @profile.full_name.split[0]
  .row.mt-2
    .col-12
      %span{class: 'font-question'}¿Cuantos cafés?
  #notice= render 'shared/alertsuccess' if (flash[:notice])
  .row.mt-2
    .col-12
      .card
        .row.select-qty
          .col-2.text-right.ml-3
            = image_tag ('coffee_donation.svg'), class: 'mt-2'
          .col-1.text-center
            X
          .col-8.mt-2
            %input{type: 'radio', name: 'multiplier', class: 'radio', value:"#{@profile.multia}", id: 'r1'}
              %span{class: 'position-number mr-2'}="#{@profile.multia}"
            %input{type: 'radio', name: 'multiplier', class: 'radio', value:"#{@profile.multib}", id: 'r2'}
              %span{class: 'position-number mr-2'}="#{@profile.multib}"
            %input{type: 'radio', name: 'multiplier', class: 'radio', value:"#{@profile.multic}", id: 'r3'}
              %span{class: 'position-number mr-2'}="#{@profile.multic}"
            %input{type: 'radio', name: 'multiplier', class: 'radio', value:"#{@profile.multid}", id: 'r4'}
              %span{class: 'position-number-d mr-2'}="#{@profile.multid}"
        .row.mb-3
          .col-6
            %span{class: 'font-little-price ml-3', id:"#{@profile.coffee_price}"}="#{@profile.coffee_price} " + "#{@profile.currency}"
          .col-6
            %span{class: 'font-total-title'}Total:
            %span{class: 'font-total-price'}= "0 #{@profile.currency}"
            %span{class: 'font-total-price', id:" #{@profile.currency}"}
  .row.justify-content-center
    .col-12
      .card.mt-2
        .card-title.mt-2
          .row
            .col.ml-3
              %span{class: 'font-donation-title-form'}Datos de
              %span{class: 'font-donation-title-form'}= name
          .card-body
          -@accounts.each do |account|
            .row
              .col.ml-3
                %span{class: 'font-show'} Entidad:
                %span{class: 'font-show-data'}= account.bankname
            .row
              .col.ml-3
                %span{class: 'font-show mt-3'} Email:
                %span{class: 'font-show-data'}= account.owner_email
            .row
              .col.ml-3
                %span{class: 'font-show'} N° de cuenta:
                %span{class: 'font-show-data'}= account.account_number
            .row
              .col.ml-3
                %span{class: 'font-show'} RIF o cédula:
                %span{class: 'font-show-data'}= account.identification_number
            .row.form-group
              .col.ml-3
                %span{class: 'font-show'} Tipo de cuenta:
                %span{class: 'font-show-data'}= account.kind
            %hr
          .row
            .col.ml-3
              %span{class: 'font-show'}Entidad:
              %span{class: 'font-show-data'}Paypal
          .row.form-group
            .col.ml-3
              %span{class: 'font-show'}Email:
              - @paypals.each do |paypal|
                %span{class: 'font-show-data'}= paypal.email
  = form_with(model: [@profile, @donation], local: true ) do |form|
    - if @donation.errors.any?
      #error_explanation.alert.alert-danger.alert-dismissible.fade.show.font-happy-alert
        %h4= "#{pluralize(@donation.errors.count, "error")} al intentar enviar donación:"
        %ul
          - @donation.errors.full_messages.each do |message|
            %li= message
        %button.close{ 'data-dismiss': 'alert' }
          %span x
    .row.justify-content-center
      .col-12
        .card.mt-2
          .row.form-group.justify-content-center
            .col-11.form-label.mt-3
              %label{class: 'font-donation-title-form'}Tus Datos
              .row.form-group.justify-content-center
                .col-11.form-label
                  = form.label :full_name, 'Nombre', class: 'font-show-data'
                  = form.text_field :full_name, {class: 'form-control', required: 'true'}
              .row.form-group.justify-content-center
                .col-11.form-label
                  = form.label :role, 'Ocupación', class: 'font-show-data'
                  = form.text_field :role, {class: 'form-control', required: 'true'}
              .row.form-group.justify-content-center
                .col-11.form-label
                  = form.label :gretting_message, 'Mensaje de agradecimiento', class: 'font-show-data'
                  = form.text_area :gretting_message, {class: 'form-control mb-5', required: 'true'}
                  - @donation.kind = '0'
                  = form.hidden_field :kind
    .row.showprofilefooter.d-flex.fixed-bottom
      .col-12.textfootermobile.d-flex.align-items-center.justify-content-center
        = form.submit "¡Listo! Notificar a #{name}", {id: 'button-submit'}