config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index' #Esta es la que deberia ir, vista home
  resources :profiles do
  	resources :images
    resources :bank_accounts
    resources :paypal_accounts
    resources :coffee_donations
    resources :hug_donations
    resources :donations
    get 'donate', to: 'donations#index'
    get 'greetings', to: 'donations#greetings'
  end
end

app/models/image.rb
class Image < ApplicationRecord
	enum visible: {'0': 'false', '1': 'true'}

  belongs_to :profile
  has_one_attached :picture

  validates :subtitle, :picture, presence: true
  validate :correct_file_type
  validate :add_picture?

  private

  def correct_file_type
    if picture.attached? && !picture.content_type.in?(%w(image/jpg image/jpeg image/png image/svg+xml))
      errors.add(:picture, 'Seleccionar solo archivos con extensión .jpg / .jpeg / .png / .svg')
    end
  end

  def add_picture?
    errors.add(:picture, 'debe ser incluida.') unless picture.attached?
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	layout 'admin'
	before_action :new_user_block
	before_action :set_image, only: [:edit, :update, :destroy]
	before_action :set_profile, except: [:index, :create]
	before_action :set_current_user_profile

	def index
		@profile = Profile.find(params[:profile_id])
    @images = @profile.images.where(profile_id: @profile)
	end

	def new
		@profile = Profile.find(params[:profile_id])
		@image = Image.new()
	end

	def edit

	end

	def create
		@profile = Profile.find(params[:profile_id])
    @image = @profile.images.build(image_params)
    respond_to do |format|
      if @image.save
        format.html { redirect_to profile_images_path, notice: '¡ Imagen Agregada Correctamente !' }
      else
        format.html { render :edit }
      end
    end
	end

	def update
		respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to profile_images_path(@image.profile), notice: '¡ Imagen Actualizada Correctamente !' }
      else
        format.html { render :edit }
      end
    end
	end

	def destroy
		respond_to do |format|
      if @image.destroy
        format.html { redirect_to profile_images_path, notice: '¡ Imagen del carrusel eliminada !'}
      else
        format.html { redirect_to profile_images_path, notice: '¡ No se pudo eliminar la imagen !'}
      end
	  end
	end

	private

	def set_image
		@image = Image.find(params[:id])
	end

	def set_profile
    @profile = Profile.find_by(params[:profile_id])
  end

	def image_params
		params.require(:image).permit(:subtitle, :visible, :picture)
	end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/edit.html.haml
.row.justify-content-center
  = render 'shared/imageform', locals: {profile: @profile, image: @image}

app/views/images/index.html.haml
.row
  .col-4.mt-3
    .font-roboto-title Carousel de Imágenes
  .col-3.offset-5.mt-5.text-right
    .btn.btn-lg.sectionadminformbutton
      = link_to "Agregar", new_profile_image_path(@profile.id), class: 'linkbutton'
%hr
#notice= render 'shared/alertsuccess' if (flash[:notice])
.row.mt-4
  .col
    .card.cardimages.mb-5.mt-2
      .card-header#cardimagesheader
        .containercardheadertext
          .cardheadertext
            Imágenes
      .card-body
        -if @images.blank?
          %hr
          .row
            .col-4.offset-4.mt-4.imagesemptystate
              .row.emptystateimage
                .col-12
                  = image_tag ('imgesemptystate.svg')
              .emptystateimagetext.mb-3
                Aún no tienes imágenes para mostrar en tu perfil.
        -else
          .row.mt-2
            .col-2.offset-1.text-center
              Imagen
            .col-7.text-center
              Subtítulo
            .col-2.text-center
              Opciones
          %hr
          - @images.each do |image|
            .row.mb-5.mt-5
              .col-2.offset-1.cardbodyimage
                = image_tag (url_for(image.picture)), class: 'pruebal'
              .col-7.cardbodytext
                = image.subtitle
              .col-2.cardbodyoptionsmenu
                .dropdown.dropleft
                  %button#dropdownMenuButton.btn{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
                    = image_tag 'cardmenubutton.svg', class: 'cardmenubutton'
                  .dropdown-menu#hola{"aria-labelledby" => "dropdownMenuButton"}
                    .dropdown-item#colorpink
                      =link_to edit_profile_image_path(@profile.id,image), class: 'cardmenubuttonpopupitem', id: 'editbutton' do
                        .row
                          .col-3
                            = image_tag 'pencil.svg'
                          .col-9
                            Editar
                    .dropdown-item#colorpink
                      =link_to profile_image_path(@profile.id,image), method: :delete, data: { confirm: '¿Esta seguro de eliminar esta imagen?'}, class: 'cardmenubuttonpopupitem', id: 'editbutton' do
                        .row
                          .col-3
                            = image_tag 'bin2.svg'
                          .col-9
                            Eliminar
            %hr
    .row
      .col.mb-5
        %hr

app/views/images/new.html.haml
.row.justify-content-center
  = render 'shared/imageform', locals: {profile: @profile, image: @image}